language: crystal

env:
  global:
    - USER="isaced"
    - EMAIL="isaced@163.com"
    - REPO="crystal-web-framework-stars"
    - GH_REPO="github.com/${USER}/${REPO}.git"

script:
  - crystal list2md.cr

after_success:
  - ls
  - git status
  - git config user.email ${EMAIL}
  - git config user.name ${USER}
  - git checkout master
  - git add README.md
  - git commit -m "Auto update"
  - git push "https://${github_access_token}@${GH_REPO}" master
