language: python
python: 3.6

env:
  global:
    - USER="isaced"
    - EMAIL="isaced@163.com"
    - REPO="crystal-web-framework-stars"
    - GH_REPO="github.com/${USER}/${REPO}.git"

install:
  - pip install requests

script:
  - python list2md.py

after_success:
  - git config user.email ${EMAIL}
  - git config user.name ${USER}
  - git add README.md
  - git commit -m "Auto update"
  - git push "https://${github_access_token}@${GH_REPO}" master > /dev/null 2>&1
