name: Auto Update CI

on:
  schedule:
    - cron: "0 0 * * SUN"

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal:nightly-alpine

    steps:
    - uses: actions/checkout@v2
      
    - name: Run Crystal Script
      run: crystal list2md.cr
    
    - name: Commit & Push
      env:
        USER: isaced
        EMAIL: isaced@163.com
      run: |
        git status
        git remote -v
        git config user.email $EMAIL
        git config user.name $USER
        git checkout master
        git add README.md
        git commit -m "Auto update"
        git push
        
