name: Auto Update CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal:nightly-alpine

    steps:
    - uses: actions/checkout@v2
  
    - name: git version
      run: git --version
      
    - name: Run Crystal Script
      run: crystal list2md.cr
    
    - name: Commit & Push
      run: |
        git status
        git remote -v
        git config user.email $EMAIL
        git config user.name $USER
        git checkout master
        git add README.md
        git commit -m "Auto update"
        git push "https://${{ secrets.ROBOT_GITHUB_TOKEN }}@$GITHUB_REPOSITORY" master
      env:
        USER: isaced
        EMAIL: isaced@163.com
        
