name: Crystal CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest
    
    container:
      image: crystallang/crystal
    
    steps:
    - uses: actions/checkout@v1
    - name: list2md
      run: crystal list2md.cr
    - name: Auto Commit changed files
      uses: stefanzweifel/git-auto-commit-action@v1.0.0
      env:
        COMMIT_MESSAGE: "Auto update"
        COMMIT_AUTHOR_NAME: "isaced"
        COMMIT_AUTHOR_EMAIL: "isaced@163.com"
